name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y freeglut3-dev libglew-dev
    - name: Build Project
      run: |
        cd $(OF_ROOT)/apps/myApps/$(PROJECT_NAME)
        make
    - name: Upload Binary
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: $(PROJECT_NAME)
        path: bin/